using System.ComponentModel;

namespace Hexagon.ALI.Analysis.Common.Enums
{
    public enum RestraintType
    {
        [Description("ANC")] ANC = 1,
        [Description("X")] X,
        [Description("Y")] Y,
        [Description("Z")] Z,
        [Description("RX")] RX,
        [Description("RY")] RY,
        [Description("RZ")] RZ,
        [Description("Guide")] Guide,
        [Description("LIM")] LIM,
        [Description("XSNB")] XSNB,
        [Description("YSNB")] YSNB,
        [Description("ZSNB")] ZSNB,
        [Description("+X")] PX,
        [Description("+Y")] PY,
        [Description("+Z")] PZ,
        [Description("-X")] NX,
        [Description("-Y")] NY,
        [Description("-Z")] NZ,
        [Description("+RX")] PRX,
        [Description("+RY")] PRY,
        [Description("+RZ")] PRZ,
        [Description("-RX")] NRX,
        [Description("-RY")] NRY,
        [Description("-RZ")] NRZ,
        [Description("+LIM")] PLIM,
        [Description("-LIM")] NLIM,
        [Description("XROD")] XROD,
        [Description("YROD")] YROD,
        [Description("ZROD")] ZROD,
        [Description("+XROD")] PXROD,
        [Description("+YROD")] PYROD,
        [Description("+ZROD")] PZROD,
        [Description("-XROD")] NXROD,
        [Description("-YROD")] NYROD,
        [Description("-ZROD")] NZROD,
        [Description("X2")] X2,
        [Description("Y2")] Y2,
        [Description("Z2")] Z2,
        [Description("RX2")] RX2,
        [Description("RY2")] RY2,
        [Description("RZ2")] RZ2,
        [Description("+X2")] PX2,
        [Description("+Y2")] PY2,
        [Description("+Z2")] PZ2,
        [Description("-X2")] NX2,
        [Description("-Y2")] NY2,
        [Description("-Z2")] NZ2,
        [Description("+RX2")] PRX2,
        [Description("+RY2")] PRY2,
        [Description("+RZ2")] PRZ2,
        [Description("-RX2")] NRX2,
        [Description("-RY2")] NRY2,
        [Description("-RZ2")] NRZ2,
        [Description("XPSR")] XSPR,
        [Description("YSPR")] YSPR,
        [Description("ZSPR")] ZSPR,
        [Description("+XSNB")] PXSNB,
        [Description("+YSNB")] PYSNB,
        [Description("+ZSNB")] PZSNB,
        [Description("-XSNB")] NXSNB,
        [Description("-YSNB")] NYSNB,
        [Description("-ZSNB")] NZSNB,
        [Description("Displ. Reaction")] DisplReaction,
        [Description("User Design VSH")] UserVSH,
        [Description("User Design CSH")] UserCSH,
        [Description("Prog Design VSH")] ProgVSH,
        [Description("Prog Design CSH")] ProgCSH,
        [Description("Prog Design RIGD ROD")] ProgRigidRod,
        [Description("VSH Redesign")] VSHRedesign,
        [Description("Dynamic Snubber")] DynamicSnubber,
        [Description("DYN Frict. Restr")] DYNFricRestr
    }
}
